book_library/config/routes.rb
Rails.application.routes.draw do
  resources :books
  # resources :users, only: %i(index new create)
  resources :users
  get 'admin' => 'admin/books#index'
  get 'admin/:id' => 'admin/books#show'
  post 'admin' => 'admin/books#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book_library/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :tags, through: :taggings
end

book_library/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :books, through: :taggings
end

book_library/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

book_library/app/models/user.rb
class User < ApplicationRecord
  has_many :books
end

book_library/app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

  # index action
  def index
    @book = Book.all
  end

  def show
  end

  def book_pdf
    @book = Book.find(params[:id])
    send_file @book.pdf_path,
              filename: @book.title,
              type: 'application/pdf',
              disposition: 'inline'
  end
end

book_library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

book_library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  after_save :increment_user_books_size

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    def increment_user_books_size
      self.user.increment!(:books_size)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :outline)
    end
end

book_library/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = destroy
      redirect_to users_url
  end

  before_action :set_user, only: %w(show edit update destroy)
  private 
    def set_user
      @user = User.find(params[:id])
    end

  private
  def user_params
    # prevent from injecting wroing parameter
    params.require(:user).permit(:name, :department)
  end
end

book_library/app/helpers/application_helper.rb
module ApplicationHelper

  def conv_break(text)
    return if text.nil?
    text.gsub!(/\r\n/, '<br>')
    text.gsub!(/\n|\r/, '<br>')
    sanitize(text, tags: %w(br))
  end
end

book_library/app/helpers/books_helper.rb
module BooksHelper
end

book_library/app/helpers/users_helper.rb
module UsersHelper
end

book_library/app/views/admin/books/index.html.slim
p#notice
  = notice
h1
  | Books
table
  thead
    tr
      th
        | Title
      th
        | Author
      th
        | Outline
      th[colspan="3"]
br
= link_to 'New Book', new_book_path

book_library/app/views/admin/books/show.html.slim
p#notice
  = notice
= debug @params

book_library/app/views/books/_form.html.slim
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      h2
        = pluralize(book.errors.count, "error")
        |  prohibited this book from being saved:
      ul
        - book.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title, id: :book_title
  .field
    = form.label :author
    = form.text_field :author, id: :book_author
  .field
    = form.label :outline
    = form.text_area :outline, id: :book_outline
  .actions
    = form.submit

book_library/app/views/books/edit.html.slim
h1
  | Editing Book
= render 'form', book: @book
= link_to 'Show', @book
|  | 
= link_to 'Back', books_path

book_library/app/views/books/index.html.erb
  <h1>ERB!</h1>

book_library/app/views/books/index.html.slim
p#notice
  = notice
h1
  | Books
table
  thead
    tr
      th
        | Title
      th
        | Author
      th
        | Outline
      th[colspan="3"]
  tbody
    - @books.each do |book|
      tr
        td
          = book.title
        td
          = book.author
        td
          = book.outline
        td
          = link_to 'Show', book
        td
          = link_to 'Edit', edit_book_path(book)
        td
          = link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Book', new_book_path

book_library/app/views/books/new.html.slim
h1
  | New Book
= render 'form', book: @book
= link_to 'Back', books_path

book_library/app/views/books/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @book.title
p
  strong
    | Author:
  = @book.author
p
  strong
    | Outline:
  = @book.outline
= link_to 'Edit', edit_book_path(@book)
|  | 
= link_to 'Back', books_path

book_library/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BookLibrary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

book_library/app/views/users/_form.html.slim
= form_for(@user) do |f|
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :department
    br
    = f.text_field :department
  .actions
    = f.submit

book_library/app/views/users/edit.html.slim
h1
  | ユーザー編集
= render 'form'
= link_to '編集', edit_user_path
= link_to '削除', user_path(@user), :method => 'DELETE'

book_library/app/views/users/index.html.slim
h1
  | 利用者一覧
table
  thead
    tr
      th
        | 氏名
      th
        | 部署
  tbody
    - @users.each do |user|
      tr
        td
          = link_to user.name, user_path(user)
        td
          = user.department
    = link_to '新規ユーザ登録', new_user_path

book_library/app/views/users/new.html.slim
h1
  | 新規利用者
= render 'form'
= link_to 'Back', users_path

book_library/app/views/users/show.html.slim
p
  strong
    | 氏名:
  = @user.name
p
  strong
    | 部署:
  = @user.department